## For more details refer to: http://tsamni.com/post/84515089035/sidekiq-performing-background-or-delayed-jobs-with
# config/redis.yml
# Redis db configuration file
# development environment
development:
    host: 'localhost'
    port: '6379'

# production environment
production:
    host: 'redis.ubitru.com'
    port: '6379'

staging:
    host: 'localhost'
    port: '6379'
