production:
  solr:
    hostname: solr.ubitru.com
    port: 8983
    log_level: WARNING
    path: /solr/default

staging:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/default

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test